[package]
name = "tt-datasheet"
version = "1.0.0"
authors = ["Kristaps Jurkans <kris.jurkans@gmail.com>"]
license = "Apache-2.0"
description = "Tiny Tapeout Datasheet Template"
repository = "?"
keywords = ["TinyTapeout"]
entrypoint = "src/datasheet.typ"
exclude = ["images"]