[package]
name = "tt-datasheet"
version = "1.0.0"
authors = ["Kristaps Jurkans <kris.jurkans@gmail.com>"]
license = "?"
description = "?"
repository = "?"
keywords = ["TinyTapeout"]
#categories = ["thesis"]
entrypoint = "src/datasheet.typ"
exclude = ["images"]

[template]
path = "template"
entrypoint = "main.typ"
#thumbnail = "images/titlepage.png"